# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d7e2eef7-8bb1-4d02-9b1f-437eaf902f2e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/06B5-9FDE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/hdd" =
    { device = "/dev/disk/by-uuid/d1b55889-68c0-462a-827a-8d01b1b1e9d4";
      fsType = "ext4";
      options = [ "nofail" "x-gvfs-show" "x-gvfs-name=HDD" ];
    };

  fileSystems."/media/windows" =
    { device = "/dev/disk/by-uuid/01DCCF4AEEDB20E0";
      fsType = "ntfs3";
      options = [ "nofail" "force" "x-gvfs-show" "x-gvfs-name=Windows" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
