
# For more configs and info check the mpv docs  https://mpv.io/manual/stable/


# Added sane defaults  ------------------------------------------------------------------------------------------------

keep-open                                                                    # dont close mpv after playing a video
loop-playlist=inf                                                            # repeat video or playlist when ends
hr-seek=yes                                                                  # more precise left mouse drag seek


# Subtitles configuration
sub-auto=all
sub-font-size=46

sub-color="#FFFFFF"                                                          # Set subtitle color (white)
sub-border-size=3                                                            # Add border for readability
sub-shadow-offset=1                                                          # Add subtle shadow
sub-shadow-color="#000000"                                                   # Shadow color
