name: "Pre-build PR for cache"

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, nix, harmonia]
    strategy:
      matrix:
        host: [laptop, raspberry-pi, dobby, microvm]
    steps:
      - uses: actions/checkout@v7
      - run: nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" --print-out-paths --no-link
      - run: nix copy --to file:///mnt/hdd/nix ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"
